services:
  nestjs:
    build:
      dockerfile: ./docker-local/Dockerfile
      context: ../
    container_name: loki-nestjs
    volumes:
      - ../:/usr/src/app
    env_file: ../.env
    command: npm run start:dev
    ports:
      - 3010:3010
      - 9229:9229
    networks:
      - testnetwork

networks:
  testnetwork:
    external: true